baseurl = "https://100awsprojects.com"
disablePathToLower = false
languageCode = "en-us"
title = "100 AWS Projects"
theme = "hugo-octopress"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# disqusShortname = "Your disqus shortname"

# Number of blog posts in each pagination page
paginate = 20

[permalinks]
# Configures post URLs
post = "/post/:year-:month-:day-:title/"

# Make tags and categories work
[indexes]
  tag = "tags"
  category = "categories"

[params]

  customCSS = ["/css/table.css"]

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true

  tableOfContents = true

  # Author's name (appears in meta tags and under posts)
  author = "Rajaram Kumar"

  # This text appears in site header under website title
  subtitle = "AWS Projects to get you started"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so it was added to index.html manually
  #continueReadingText = "Would you like to know more?"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-XXXXX-X"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  defaultDescription = ""

  # Populate this with your own search keywords - these will appear in meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = true

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

   # If nothing is set, then solarized_light is used
  pygmentsstyle = "solarized_dark"

  # Use internal highlighter instead of Chroma
  pygmentsUseClassic=true

  # Highlight shortcode and code fences (```) will be treated similarly
  pygmentscodefences = true

  pygmentsoptions = "linenos=inline"

  # pygments options can be added here (and in the highlight shortcode in the markdown file)
  # Hugo supports these pygments options: style, encoding, noclasses, hl_lines, linenos
  # for example: pygmentsoptions = "linenos=true"
  sidebarHeader = "Who am I ?"
  sidebarMenuEnabled = true
  sidebarText = """
  I am Rajaram Kumar , working as a Java software engineer.
  <br>
  I am interested in AWS and exploring it through projects. I have 2 AWS Certifications , Developer and Architect
  """

  github = "https://github.com/"
  bitbucket = "https://bitbucket.org/"
  gitlab = ""
  twitter = "https://twitter.com/"
  keybase = "https://keybase.io/"
  stackoverflow = ""
  linkedin = ""
  googleplus = ""
  youtube = ""
  facebook = ""
  instagram = ""

[[menu.main]]
  Name = "All Posts"
  URL = "/"
  weight = -120
  
[[menu.main]]
  name = "AWS Links"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "awslinks"
  url = "/awslinks/"

[[menu.main]]  
  url = "/tweets/"
  name = "Tweets"
  weight = -100

[[menu.main]]  
  url = "/about/"
  name = "About"
  weight = -90